### ISSUE TITLE
run train.py error

### ISSUE THREAD

**Issue by june1819** [fab-jul/L3C-PyTorch#22] opened 2020-09-16 11:49 UTC
Dear Dr.Mentzer
I can't run "python train.py -h",  but "python test.py -h" works well.
  "python train.py -h" error:  ValueError: unsupported format character 'O' (0x4f) at index 38. File "train.py", line 125, in <module>
    main(sys.argv[1:])  File "train.py", line 91, in main  flags = p.parse_args(args)

I can't run "python train.py configs/ms/cr.cf configs/dl/oi.cf log_dir -p upsampling=deconv" to train dataset. but I can run it with "python train.py configs/ms/cr.cf configs/dl/oi.cf log_dir"
Please answer my question
thank you

**Comment by fab-jul** [comment] 2020-09-19 11:13
Hi did you resolve this? It sounds like something goes wrong with encoding?

**Comment by june1819** [comment] 2020-09-19 11:44
Dear Dr.Mentzer
first question：“python train.py -h” report error in "/lib/python3.7/argparse.py". I think my python version(3.7.8) is error. What your python concrete version is？（3.7.1 ，3.7.2 or others？）
second question：what "-p upsampling=deconv" means?   The train command with "-p upsampling=deconv" reported error "ValueError: Unused params:
- upsampling"

**Comment by fab-jul** [comment] 2020-09-19 12:04
Can you print the complete stack trace of the `-h` command? Also, what's your operating system and shell?
And you should be able to train without the `-p` flag, that was just to illustrate the config parsing.

**Comment by june1819** [comment] 2020-09-19 12:11
-h command：
Traceback (most recent call last):
  File "train.py", line 125, in <module>
    main(sys.argv[1:])
  File "train.py", line 91, in main
    flags = p.parse_args(args)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 1043, in __call__
    parser.print_help()
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 2481, in print_help
    self._print_message(self.format_help(), file)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 2465, in format_help
    return formatter.format_help()
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 531, in _format_action
    help_text = self._expand_help(action)
  File "/home/zsf/anaconda3/envs/l3c_env/lib/python3.7/argparse.py", line 620, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character 'O' (0x4f) at index 38

**Comment by june1819** [comment] 2020-09-19 12:14
operating system：Ubuntu. shell: /bin/bash
I can run train command without -p. thanks for explanation

**Comment by fab-jul** [comment] 2020-09-19 15:28
Hey, thanks for the stack trace. Turns out there was a `%` in a help message causes this exception. Fixed in latest commit (4ca100eb0055ead5efa5e96138da890247d172f9).

Regarding the `-p upsampling=deconv`, I cannot reproduce your error message. But I updated the readme to make it a bit more clear that this is not the default command (9133bed5ce6497dfcffc47a78908f9d2a4fd3953)

**Comment by fab-jul** [comment] 2020-09-19 15:28
Thanks for the feedback. Let me know if you find anything else!

**Closed by fab-jul** 2020-09-19 15:28 UTC
